# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        user_adapter:
            local:
                directory: "%kernel.root_dir%/../public/uploads"
        file_excel_adapter:
            local:
                directory: "%kernel.root_dir%/../public/uploads/files"
            # awss3v3:
            #     client: Aws\S3\S3Client
            #     bucket: '%env(AWS_S3_BUCKET_NAME)%'
    filesystems:
        photo_user_fs:
            adapter: user_adapter
            mount: photo_user_fs
            visibility: public
        file_excel_fs:
            adapter: file_excel_adapter
            mount: file_excel_fs
            visibility: public