vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        photo_user:
            uri_prefix: ""
            upload_destination: photo_user_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        file_excel:
            uri_prefix: ""
            upload_destination: file_excel_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer