api_auth:
  path: /api/auth
gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
