<?php

namespace App\DataFixtures;

use App\Entity\Category;
use App\Entity\SubCategory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;

class CategoryFixtures extends Fixture
{
	public function load(ObjectManager $manager)
	{
		$names = array(
			'Agricultural and Biological Sciences' => array(
				'Agricultural and Biological Sciences (miscellaneous)',
				'Agronomy and Crop Science',
				'Animal Science and Zoology',
				'Aquatic Science',
				'Ecology, Evolution, Behavior and Systematics',
				'Food Science',
				'Forestry',
				'General Agricultural and Biological Sciences',
				'Horticulture',
				'Insect Science',
				'Plant Science',
				'Soil Science'
			),
			'Arts and Humanities' => array(
				'Archeology (arts and humanities)',
				'Arts and Humanities (miscellaneous)',
				'Classics',
				'Conservation',
				'General Arts and Humanities',
				'History',
				'History and Philosophy of Science',
				'Language and Linguistics',
				'Literature and Literary Theory',
				'Museology',
				'Music',
				'Philosophy',
				'Religious Studies',
				'Visual Arts and Performing Arts'
			),
			'Biochemistry, Genetics and Molecular Biology' => array(
				'Aging',
				'Biochemistry',
				'Biochemistry, Genetics and Molecular Biology (miscellaneous)',
				'Biophysics',
				'Biotechnology',
				'Cancer Research',
				'Cell Biology',
				'Clinical Biochemistry',
				'Developmental Biology',
				'Endocrinology',
				'General Biochemistry, Genetics and Molecular Biology',
				'Genetics',
				'Molecular Biology',
				'Molecular Medicine',
				'Physiology',
				'Structural Biology'
			),
			'Business, Management and Accounting' => array(
				'Accounting',
				'Business and International Management',
				'Business, Management and Accounting (miscellaneous)',
				'General Business, Management and Accounting',
				'Industrial Relations',
				'Management Information Systems',
				'Management of Technology and Innovation',
				'Marketing',
				'Organizational Behavior and Human Resource Management',
				'Strategy and Management',
				'Tourism, Leisure and Hospitality Management'
			),
			'Chemical Engineering' => array(
				'Bioengineering',
				'Catalysis',
				'Chemical Engineering (miscellaneous)',
				'Chemical Health and Safety',
				'Colloid and Surface Chemistry',
				'Filtration and Separation',
				'Fluid Flow and Transfer Processes',
				'General Chemical Engineering',
				'Process Chemistry and Technology'
			),
			'Chemistry' => array(
				'Analytical Chemistry',
				'Chemistry (miscellaneous)',
				'Electrochemistry',
				'General Chemistry',
				'Inorganic Chemistry',
				'Organic Chemistry',
				'Physical and Theoretical Chemistry',
				'Spectroscopy',
			),
			'Computer Science' => array(
				'Artificial Intelligence',
				'Computational Theory and Mathematics',
				'Computer Graphics and Computer-Aided Design',
				'Computer Networks and Communications',
				'Computer Science (miscellaneous)',
				'Computer Science Applications',
				'Computer Vision and Pattern Recognition',
				'General Computer Science',
				'Hardware and Architecture',
				'Human-Computer Interaction',
				'Information Systems',
				'Signal Processing',
				'Software'
			),
			'Decision Sciences' => array(
				'Decision Sciences (miscellaneous)',
				'General Decision Sciences',
				'Information Systems and Management',
				'Management Science and Operations Research',
				'Statistics, Probability and Uncertainty'
			),
			'Dentistry' => array(
				'Dental Assisting',
				'Dental Hygiene',
				'Dentistry (miscellaneous)',
				'General Dentistry',
				'Oral Surgery',
				'Orthodontics',
				'Periodontics'
			),
			'Earth and Planetary Sciences' => array(
				'Atmospheric Science',
				'Computers in Earth Sciences',
				'Earth and Planetary Sciences (miscellaneous)',
				'Earth-Surface Processes',
				'Economic Geology',
				'General Earth and Planetary Sciences',
				'Geochemistry and Petrology',
				'Geology',
				'Geophysics',
				'Geotechnical Engineering and Engineering Geology',
				'Oceanography',
				'Paleontology',
				'Space and Planetary Science',
				'Stratigraphy'
			),
			'Economics, Econometrics and Finance' => array(
				'Economics and Econometrics',
				'Economics, Econometrics and Finance (miscellaneous)',
				'Finance',
				'General Economics, Econometrics and Finance'
			),
			'Energy' => array(
				'Energy (miscellaneous)',
				'Energy Engineering and Power Technology',
				'Fuel Technology',
				'General Energy',
				'Nuclear Energy and Engineering',
				'Renewable Energy, Sustainability and the Environment'
			),
			'Engineering' => array(
				'Aerospace Engineering',
				'Architecture',
				'Automotive Engineering',
				'Biomedical Engineering',
				'Building and Construction',
				'Civil and Structural Engineering',
				'Computational Mechanics',
				'Control and Systems Engineering',
				'Electrical and Electronic Engineering',
				'Engineering (miscellaneous)',
				'General Engineering',
				'Industrial and Manufacturing Engineering',
				'Mechanical Engineering',
				'Mechanics of Materials',
				'Media Technology',
				'Ocean Engineering',
				'Safety, Risk, Reliability and Quality'
			),
			'Environmental Science' => array(
				'Ecological Modeling',
				'Ecology',
				'Environmental Chemistry',
				'Environmental Engineering',
				'Environmental Science (miscellaneous)',
				'General Environmental Science',
				'Global and Planetary Change',
				'Health, Toxicology and Mutagenesis',
				'Management, Monitoring, Policy and Law',
				'Nature and Landscape Conservation',
				'Pollution',
				'Waste Management and Disposal',
				'Water Science and Technology'
			),
			'Health Professions' => array(
				'Chiropractics',
				'Complementary and Manual Therapy',
				'Emergency Medical Services',
				'General Health Professions',
				'Health Information Management',
				'Health Professions (miscellaneous)',
				'Medical Assisting and Transcription',
				'Medical Laboratory Technology',
				'Medical Terminology',
				'Occupational Therapy',
				'Optometry',
				'Pharmacy',
				'Physical Therapy, Sports Therapy and Rehabilitation',
				'Podiatry',
				'Radiological and Ultrasound Technology',
				'Respiratory Care',
				'Speech and Hearing'
			),
			'Immunology and Microbiology' => array(
				'Applied Microbiology and Biotechnology',
				'General Immunology and Microbiology',
				'Immunology',
				'Immunology and Microbiology (miscellaneous)',
				'Microbiology',
				'Parasitology',
				'Virology'
			),
			'Materials Science' => array(
				'Biomaterials',
				'Ceramics and Composites',
				'Electronic, Optical and Magnetic Materials',
				'General Materials Science',
				'Materials Chemistry',
				'Materials Science (miscellaneous)',
				'Metals and Alloys',
				'Polymers and Plastics',
				'Surfaces, Coatings and Films'
			),
			'Mathematics' => array(
				'Algebra and Number Theory',
				'Analysis',
				'Applied Mathematics',
				'Computational Mathematics',
				'Control and Optimization',
				'Discrete Mathematics and Combinatorics',
				'General Mathematics',
				'Geometry and Topology',
				'Logic',
				'Mathematical Physics',
				'Mathematics (miscellaneous)',
				'Modeling and Simulation',
				'Numerical Analysis',
				'Statistics and Probability',
				'Theoretical Computer Science'
			),
			'Medicine' => array(
				'Anatomy',
				'Anesthesiology and Pain Medicine',
				'Biochemistry (medical)',
				'Cardiology and Cardiovascular Medicine',
				'Complementary and Alternative Medicine',
				'Critical Care and Intensive Care Medicine',
				'Dermatology',
				'Drug Guides',
				'Embryology',
				'Emergency Medicine',
				'Endocrinology, Diabetes and Metabolism',
				'Epidemiology',
				'Family Practice',
				'Gastroenterology',
				'General Medicine',
				'Genetics (clinical)',
				'Geriatrics and Gerontology',
				'Health Informatics',
				'Health Policy',
				'Hematology',
				'Hepatology',
				'Histology',
				'Immunology and Allergy',
				'Infectious Diseases',
				'Internal Medicine',
				'Medicine (miscellaneous)',
				'Microbiology (medical)',
				'Nephrology',
				'Neurology (clinical)',
				'Obstetrics and Gynecology',
				'Oncology',
				'Ophthalmology',
				'Orthopedics and Sports Medicine',
				'Otorhinolaryngology',
				'Pathology and Forensic Medicine',
				'Pediatrics, Perinatology and Child Health',
				'Pharmacology (medical)',
				'Physiology (medical)',
				'Psychiatry and Mental Health',
				'Public Health, Environmental and Occupational Health',
				'Pulmonary and Respiratory Medicine',
				'Radiology, Nuclear Medicine and Imaging',
				'Rehabilitation',
				'Reproductive Medicine',
				'Reviews and References (medical)',
				'Rheumatology',
				'Surgery',
				'Transplantation',
				'Urology'
			),
			'Multidisciplinary' => array('Multidisciplinary'),
			'Neuroscience' => array(
				'Behavioral Neuroscience',
				'Biological Psychiatry',
				'Cellular and Molecular Neuroscience',
				'Cognitive Neuroscience',
				'Developmental Neuroscience',
				'Endocrine and Autonomic Systems',
				'General Neuroscience',
				'Neurology',
				'Neuroscience (miscellaneous)',
				'Sensory Systems'
			),
			'Nursing' => array(
				'Advanced and Specialized Nursing',
				'Assessment and Diagnosis',
				'Care Planning',
				'Community and Home Care',
				'Critical Care Nursing',
				'Emergency Nursing',
				'Fundamentals and Skills',
				'General Nursing',
				'Gerontology',
				'Issues, Ethics and Legal Aspects',
				'LPN and LVN',
				'Leadership and Management',
				'Maternity and Midwifery',
				'Medical and Surgical Nursing',
				'Nurse Assisting',
				'Nursing (miscellaneous)',
				'Nutrition and Dietetics',
				'Oncology (nursing)',
				'Pathophysiology',
				'Pediatrics',
				'Pharmacology (nursing)',
				'Psychiatric Mental Health',
				'Research and Theory',
				'Review and Exam Preparation'
			),
			'Pharmacology, Toxicology and Pharmaceutics' => array(
				'Drug Discovery',
				'General Pharmacology, Toxicology and Pharmaceutics',
				'Pharmaceutical Science',
				'Pharmacology',
				'Pharmacology, Toxicology and Pharmaceutics (miscellaneous)',
				'Toxicology'
			),
			'Physics and Astronomy' => array(
				'Acoustics and Ultrasonics',
				'Astronomy and Astrophysics',
				'Atomic and Molecular Physics, and Optics',
				'Condensed Matter Physics',
				'General Physics and Astronomy',
				'Instrumentation',
				'Nuclear and High Energy Physics',
				'Physics and Astronomy (miscellaneous)',
				'Radiation',
				'Statistical and Nonlinear Physics',
				'Surfaces and Interfaces'
			),
			'Psychology' => array(
				'Applied Psychology',
				'Clinical Psychology',
				'Developmental and Educational Psychology',
				'Experimental and Cognitive Psychology',
				'General Psychology',
				'Neuropsychology and Physiological Psychology',
				'Psychology (miscellaneous)',
				'Social Psychology'
			),
			'Social Sciences' => array(
				'Anthropology',
				'Archeology',
				'Communication',
				'Cultural Studies',
				'Demography',
				'Development',
				'Education',
				'Gender Studies',
				'General Social Sciences',
				'Geography, Planning and Development',
				'Health (social science)',
				'Human Factors and Ergonomics',
				'Law',
				'Library and Information Sciences',
				'Life-span and Life-course Studies',
				'Linguistics and Language',
				'Political Science and International Relations',
				'Public Administration',
				'Safety Research',
				'Social Sciences (miscellaneous)',
				'Sociology and Political Science',
				'Transportation',
				'Urban Studies'
			),
			'Veterinary' => array(
				'Equine',
				'Food Animals',
				'General Veterinary',
				'Small Animals',
				'Veterinary (miscellaneous)'
			)
		);
		foreach ($names as $key => $name) {
			$category = new Category();
			$category->setTitle($key);
			$manager->persist($category);
			foreach($name as $sub) {
				$subCategory = new SubCategory();
				$subCategory->setTitle($sub);
				$subCategory->setCategory($category);
				$manager->persist($subCategory);
			}
		}
		$manager->flush();
	}
}
